### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by AmeenAli** [HennyJie/IBGNN#1]
Hi,
Awesome work indeed!

A question about the datasets,  where can i find the following files ; 

datasets/New_Node_AAL90.txt
datasets/New_Node_Brodmann82.txt
datasets/New_Node_PPMI.txt
datasets/New_Node_PPMI.txt

Thanks,

**Comment by HennyJie** [comment]
Hi Ameen, 
Thanks for your question! Those files are used for visualization using the BrainNetViewer software. We have now included them in our repository. See https://github.com/HennyJie/IBGNN/tree/master/datasets.
